/**
 * `gitglow commit` action.
 *
 * Workflow:
 *  1. Check for staged files.
 *  2. Run security scanner (blocks on violations).
 *  3. Generate commit message (AI or mock).
 *  4. Validate the message format.
 *  5. Prompt the user: commit / edit / regenerate / abort.
 *
 * Non-interactive flags:
 *  --yes       Commit directly with the generated message (skips prompt).
 *  --dry-run   Print the message but do not commit.
 *  --no-ai     Force mock mode regardless of OPENAI_API_KEY.
 */
import chalk from 'chalk';
import ora from 'ora';
import prompts from 'prompts';
import { hasStagedFiles, getStagedDiff, makeCommit } from '../utils/git.js';
import { executeScan } from './security.js';
import { loadConfig } from '../utils/config.js';
import { generateCommitMessage } from '../utils/openai.js';
import { validateCommitMessage } from '../utils/validate.js';
import { GitError, CLIError } from '../types/index.js';

export interface CommitOptions {
  forceMock?: boolean;
  noAi?: boolean;
  yes?: boolean;
  dryRun?: boolean;
}

/** Print the privacy notice once per command invocation when AI is active */
function printPrivacyNotice(): void {
  console.log(
    chalk.yellow(
      '\n⚠  Privacy notice: Your staged diff will be sent to the OpenAI API to ' +
        'generate a commit message. Use --no-ai to keep diffs local.\n',
    ),
  );
}

export async function commitAction(options: CommitOptions): Promise<void> {
  // 1. Staged files check
  let hasStaged: boolean;
  try {
    hasStaged = hasStagedFiles();
  } catch (err) {
    if (err instanceof GitError) {
      console.error(chalk.red(`✗ Git error: ${err.message}`));
      throw new CLIError('', 1);
    } else {
      console.error(chalk.red('✗ Unexpected error checking staged files.'), err);
      throw new CLIError('Unexpected error checking staged files.', 1);
    }
  }

  if (!hasStaged) {
    console.log(
      chalk.yellow(
        '⚠  No staged files found. Use `git add <file>` to stage changes before committing.',
      ),
    );
    throw new CLIError('', 0);
  }

  // 2. Load diff + config
  const config = loadConfig();
  const maxBytes = config.maxDiffBytes ?? 20_000;
  const { diff } = getStagedDiff(maxBytes);

  // 3. Security scan (blocks if violations found)
  if (!executeScan(diff, config)) {
    throw new CLIError('Commit blocked due to security scan violations.', 1);
  }

  // 4. Privacy notice for AI mode
  const useMock =
    options.forceMock ||
    options.noAi ||
    process.env.NODE_ENV === 'test' ||
    !process.env.OPENAI_API_KEY;

  if (!useMock) {
    printPrivacyNotice();
  }

  // 5. Generate + validate in a loop (supports regenerate)
  let aiMessage = '';
  let attempts = 0;
  let regenerate = true;

  // eslint-disable-next-line no-unmodified-loop-condition
  while (regenerate) {
    regenerate = false;
    attempts++;
    const spinner = ora(
      attempts === 1
        ? 'Analyzing diff and drafting commit message…'
        : 'Regenerating commit message…',
    ).start();

    let raw = '';
    let validation: ReturnType<typeof validateCommitMessage>;
    try {
      raw = await generateCommitMessage(diff, config, useMock);
      validation = validateCommitMessage(raw, config.conventionalTypes);

      if (!validation.valid) {
        spinner.warn(
          `Generated message failed validation: ${validation.error} ` +
            `(displaying anyway for manual review)`,
        );
        aiMessage = validation.message || raw;
      } else {
        spinner.succeed('Commit message ready.');
        aiMessage = validation.message;
      }
    } catch (err) {
      spinner.fail('Failed to generate commit message.');
      console.error(
        chalk.red(err instanceof Error ? err.message : String(err)),
      );
      if (!useMock) {
        console.log(chalk.yellow('Tip: use --no-ai to run in offline mock mode.'));
      }
      throw new CLIError('Failed to generate commit message.', 1);
    }

    console.log(chalk.cyan.bold('\n--- Suggested Commit Message ---'));
    console.log(chalk.green(aiMessage));
    console.log(chalk.cyan.bold('--------------------------------\n'));

    if (useMock) {
      console.log(chalk.dim('[Mock mode – not generated by AI]'));
    } else {
      console.log(chalk.dim('[AI-generated – verify before committing]'));
    }

    // Non-interactive: --yes or --dry-run
    if (options.yes || options.dryRun) {
      if (options.dryRun) {
        console.log(chalk.yellow('Dry-run mode: commit NOT created.'));
        throw new CLIError('', 0);
      }
      if (!validation.valid) {
        throw new CLIError(
          `Generated commit message failed validation: ${validation.error}. ` +
            `Aborting automatic commit (--yes).`,
          1,
        );
      }
      makeCommit(aiMessage);
      console.log(chalk.green.bold('✓ Committed successfully.'));
      return;
    }

    // Interactive prompt
    const response = await prompts({
      type: 'select',
      name: 'action',
      message: 'What would you like to do?',
      choices: [
        { title: '✅ Commit with this message', value: 'commit' },
        { title: '✏️  Edit before committing', value: 'edit' },
        { title: '🔄 Regenerate (new AI request)', value: 'regenerate' },
        { title: '⛔ Abort', value: 'abort' },
      ],
    });

    if (response.action === 'commit') {
      makeCommit(aiMessage);
      console.log(chalk.green.bold('✓ Committed successfully.'));
      return;
    } else if (response.action === 'edit') {
      const editResponse = await prompts({
        type: 'text',
        name: 'customMessage',
        message: 'Edit commit message:',
        initial: aiMessage,
      });
      if (editResponse.customMessage?.trim()) {
        makeCommit(editResponse.customMessage.trim());
        console.log(chalk.green.bold('✓ Committed with custom message.'));
      } else {
        console.log(chalk.yellow('Commit cancelled (empty message).'));
      }
      return;
    } else if (response.action === 'regenerate') {
      // Loop continues – will call generateCommitMessage again
      regenerate = true;
      continue;
    } else {
      console.log(chalk.yellow('Commit operation cancelled.'));
      return;
    }
  }
}
