/**
 * `gitglow pr <baseBranch>` action.
 *
 * Compares the current branch against baseBranch and generates a
 * structured Markdown Pull Request description.
 *
 * Non-interactive flags:
 *  --no-ai         Force mock mode regardless of OPENAI_API_KEY.
 *  --no-clipboard  Do not copy the result to the clipboard.
 *  --output <file> Write the PR description to a file instead of / in addition to stdout.
 *  --dry-run       Print the description but do not write to file or clipboard.
 */
import chalk from 'chalk';
import ora from 'ora';
import clipboardy from 'clipboardy';
import fs from 'fs';
import { getBranchDiff } from '../utils/git.js';
import { loadConfig } from '../utils/config.js';
import { generatePRDescription } from '../utils/openai.js';
import { validatePRDescription } from '../utils/validate.js';
import { GitError, CLIError } from '../types/index.js';

export interface PrOptions {
  forceMock?: boolean;
  noAi?: boolean;
  noClipboard?: boolean;
  output?: string;
  dryRun?: boolean;
}

function printPrivacyNotice(): void {
  console.log(
    chalk.yellow(
      '\n⚠  Privacy notice: Your branch diff will be sent to the OpenAI API to ' +
        'generate a PR description. Use --no-ai to keep diffs local.\n',
    ),
  );
}

export async function prAction(baseBranch: string, options: PrOptions): Promise<void> {
  // Load config before git ops so we can use maxDiffBytes
  const config = loadConfig();
  const maxBytes = config.maxDiffBytes ?? 20_000;

  // Get branch diff (validates baseBranch internally via git check-ref-format)
  let diff: string;
  let commits: string;
  try {
    const result = getBranchDiff(baseBranch, maxBytes);
    diff = result.diff;
    commits = result.commits;
  } catch (err) {
    if (err instanceof GitError) {
      console.error(chalk.red(`✗ Git error: ${err.message}`));
      throw new CLIError('', 1);
    } else {
      console.error(chalk.red('✗ Unexpected error getting branch diff.'), err);
      throw new CLIError('Unexpected error getting branch diff.', 1);
    }
  }

  if (!diff) {
    console.log(
      chalk.yellow(
        `⚠  No changes found between "${baseBranch}" and the current branch. ` +
          `Make sure you have committed changes and the base branch exists.`,
      ),
    );
    throw new CLIError('', 0);
  }

  const useMock =
    options.forceMock ||
    options.noAi ||
    process.env.NODE_ENV === 'test' ||
    !process.env.OPENAI_API_KEY;

  if (!useMock) {
    printPrivacyNotice();
  }

  const spinner = ora('Synthesizing PR description…').start();
  let prMarkdown: string;

  try {
    prMarkdown = await generatePRDescription(diff, commits, config, useMock);
    spinner.succeed('PR description ready.');

    const prValidation = validatePRDescription(prMarkdown);
    if (!prValidation.valid) {
      spinner.warn(
        `Generated PR description is missing standard sections:\n` +
          prValidation.errors.map(e => `  - ${e}`).join('\n'),
      );
    }
  } catch (err) {
    spinner.fail('Failed to generate PR description.');
    console.error(chalk.red(err instanceof Error ? err.message : String(err)));
    if (!useMock) {
      console.log(chalk.yellow('Tip: use --no-ai to run in offline mock mode.'));
    }
    throw new CLIError('Failed to generate PR description.', 1);
  }

  // Output
  console.log(chalk.cyan.bold('\n--- Pull Request Description (Markdown) ---'));
  console.log(prMarkdown);
  console.log(chalk.cyan.bold('-------------------------------------------\n'));

  if (useMock) {
    console.log(chalk.dim('[Mock mode – not generated by AI. Update before submitting.]'));
  }

  if (options.dryRun) {
    console.log(chalk.yellow('Dry-run mode: no file written, no clipboard copy.'));
    return;
  }

  // Write to file if --output specified
  if (options.output) {
    try {
      fs.writeFileSync(options.output, prMarkdown, 'utf8');
      console.log(chalk.green(`✓ PR description written to: ${options.output}`));
    } catch (err) {
      const errMsg = `Failed to write PR description to "${options.output}": ${err instanceof Error ? err.message : String(err)}`;
      console.error(chalk.red(`✗ ${errMsg}`));
      throw new CLIError(errMsg, 1);
    }
  }

  // Clipboard
  if (!options.noClipboard) {
    try {
      clipboardy.writeSync(prMarkdown);
      console.log(chalk.green.bold('✓ PR description copied to clipboard.'));
    } catch {
      console.log(
        chalk.yellow('⚠  Clipboard copy failed. Use --output <file> to save the description.'),
      );
    }
  }
}
